---
title: Lend First Home Loans
timezone: UTC
collections:
  posts:
    title: Blog
    output: true
  loan-options:
    title: Loan options
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: about
  values:
    layout: post
    permalink: "/:collection/:path/"
- scope:
    path: ''
    type: loan-options
  values:
    layout: page
    permalink: "/:collection/:path/"
    image: true
    lede: true
    has-javascripts: true
    offset-top: 820
    offset-bottom: 1940
- scope:
    path: ''
    type: pages
  values:
    layout: page
    has-javascripts: true
    offset-top: 820
    offset-bottom: 1300
- scope:
    path: ''
    type: posts
  values:
    layout: page
    permalink: "/:categories/:slug/"
    has-javascripts: true
    title: 
    categories: 
    type: post
    image: true
    image-align: false
    lede: true
    offset-top: 820
    offset-bottom: 1300
